import os

main_path = os.getcwd()
Export('main_path')

# Tell SCons to create our build files in the 'build' directory
VariantDir('build', 'src', duplicate=0)
SConscript('build/SConscript', 'main_path')
